version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging-todo-list-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cxher468fqlw"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
